### ISSUE TITLE
Allow folder uploads

### ISSUE THREAD

**Issue by ChappIO** [Tocabi/clearcloud#74]
How hard would it be to upload an entire folder?
This would create a new folder and upload the folder contents (recursively) into it.

**Comment by LucaScorpion** [comment]
For the `input` element there doesn't seem to be a way to do this. I only found the non-standard [webkitdirectory](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/webkitdirectory) attribute, but that allows you to _only_ select folders, not files. For drag&drop I do think it will be possible, but we'll have to check that as part of #46.
