### ISSUE TITLE
Show loading indicator when browsing

### ISSUE THREAD

**Issue by LucaScorpion** [Tocabi/clearcloud#78]
Currently when switching between libraries or browsing folders the previous file list will stay on screen, with no loading indicator whatsoever. Generally this won't be much of an issue, but I specifically noticed it when browsing my server when the HDDs were spun down, so some libraries took a couple seconds to load.

Implementation wise I'd suggest a subtle indicator (maybe something like Directus does?) rather than replacing the entire file list (as I imagine that would cause the content to jump too much), but we'd have to experiment a bit.

**Comment by ChappIO** [comment]
I don't think jumping will be an issue as our content is always the full height of the screen right?

**Comment by LucaScorpion** [comment]
True, I was thinking more about the table being empty for a split second before switching over to the next file list, rather than it just going from one list of files to the next (so `fileListA -> blank -> fileListB` vs `fileListA -> fileListB`). Wouldn't be as bad as actualy shifting content though for sure, but might still look a bit iffy. But I guess one way to find out ^^

**Comment by ChappIO** [comment]
Fair enough
